### ISSUE TITLE
Shouldn't `components(x) == (x,)` if `d` is not a composite type?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/CompositeTypes.jl#5]
Right now we have
```julia
components(x) = ()
```
But shouldn't it be
```julia
components(x) == (x,)
```
as, for example, `components(0..1)` should have a single component `0..1`?

**Comment by daanhb** [comment]
That could have been a choice, but it's not how I was currently interpreting it. Right now, a type is considered to be composite only if `length(components(x)) > 0`, in which case `components(x)` returns its components. So in DomainSets a `UnionDomain` or a `ProductDomain` would be composite, but an interval isn't.

**Comment by dlfivefifty** [comment]
`components` should then throw an error: it's misleading to say it has no components, that is, `components(0..1)` makes it look empty

**Comment by daanhb** [comment]
Throwing an error would be doable. To make `components(x) == (x,)` would invalidate a lot of the logic in the display, but that could be fixed if the change is worth it. I did not consider it at first.
